### ISSUE TITLE
8000+ synonyms for some words

### ISSUE THREAD

**Issue by mgraauw** [cltl/OpenDutchWordnet#8]
Some words yield more than 8000 synonyms. Try:
>>> from OpenDutchWordnet import Wn_grid_parser
>>> instance = Wn_grid_parser(Wn_grid_parser.odwn)
>>> syns = instance.les_lemma_synonyms('generiek')
>>> print(len(syns), list(syns)[:20], '...')
8812 ['wildkamperen', 'indiscretie', 'inbegrip', 'Noordzee', 'borstwijdte', 'Turkmeense', 'Moskou', 'onvruchtbaarheid', 'augurk', 'expresweg', 'saloondeuren', 'oud-minister', 'raclette', 'samenpakken', 'Armenië', 'werkloosheidsprobleem', 'Zevengebergte', 'luchtledige', 'spellingwijziging', 'treinstaking'] ...
>>> syns = instance.les_lemma_synonyms('kalender')
>>> print(len(syns), list(syns)[:20], '...')
8817 ['wildkamperen', 'indiscretie', 'inbegrip', 'Noordzee', 'borstwijdte', 'Turkmeense', 'Moskou', 'onvruchtbaarheid', 'augurk', 'expresweg', 'saloondeuren', 'oud-minister', 'raclette', 'samenpakken', 'Armenië', 'werkloosheidsprobleem', 'Zevengebergte', 'luchtledige', 'spellingwijziging', 'treinstaking'] ...
>>> syns = instance.les_lemma_synonyms('post')
>>> print(len(syns), list(syns)[:20], '...')
8834 ['wildkamperen', 'indiscretie', 'inbegrip', 'Noordzee', 'borstwijdte', 'Turkmeense', 'Moskou', 'onvruchtbaarheid', 'augurk', 'expresweg', 'saloondeuren', 'oud-minister', 'raclette', 'samenpakken', 'Armenië', 'werkloosheidsprobleem', 'Zevengebergte', 'luchtledige', 'spellingwijziging', 'treinstaking'] ...

Most words work fine (in al list of 90 words, 10 yield the 8000+, the others not, without any apparent logic). The xml entries in odwn_orbn_gwg-LMF_1.3.xml.gz look fine (to me) too. Is this a bug in les_lemma_synonyms?

Regards,

Marc

**Comment by stephantul** [comment]
Hey, I also encountered this problem.

This is caused by the fact that some words have `None` in their list of synsets. Because the mapping between synsets and lemmas is simply a reverse index, any lemma which has `None` in the list of synsets will return a lot of unrelated garbage.

A quick fix is to replace the line `323` in `les.py` by the following line:
`        for synset_id in [x for x in self.lemma2synsets[lemma] if x is not None]:`

This removes all `None`, and hence will not return the garbage items.
I'll submit a PR, but this should be enough for now.

**Comment by stephantul** [comment]
I submitted a PR, if you want you can copy the code I changed if the maintainers take too long to respond. Good luck!

**Comment by mgraauw** [comment]
Thanks, that will do!
